FROM rust as builder
WORKDIR /usr/src/rtrs
COPY . .
RUN cargo install --path crates/rtrs --locked --release

FROM scratch
COPY --from=builder /usr/local/cargo/bin/rtrs /rtrs
CMD ["/rtrs", "--host", "0.0.0.0","--port", "80"]
